### ISSUE TITLE
Mistaken authorship on SOAP 2021 submission

### ISSUE THREAD

**Issue by ryan-williams** [raytheonbbn/weldr#5]
Hi, I was added to https://pldi21.sigplan.org/details/SOAP-2021-papers/3/Weldr-Fusing-Binaries-for-Simplified-Analysis but have no affiliation with this project.

![screenshot of talk authors page](https://user-images.githubusercontent.com/465045/115731037-cef9f480-a354-11eb-8f5c-741a9821bd79.png)

**Comment by ajordanBBN** [comment]
Ryan - we're not sure what happened, but we have a co-author named Ryan Williams and some PLDI system seems to have automatically associated your account with it. We'll figure it out, and thanks for letting us know.

**Comment by ryan-williams** [comment]
np, it's not my first time encountering that Ryan Williams (if it's who I'm thinking of) this way 😉

**Comment by williamsryan** [comment]
I don't have permission to modify the status here, but issue is resolved. @ryan-williams
